In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
## sentences
sent=[
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am eating glass of milk',
    'understanding the meaning of words',
    'your videos are good',
]

In [4]:
sent


['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am eating glass of milk',
 'understanding the meaning of words',
 'your videos are good']

In [5]:
## define the vocabulary size
vocab_size=10000

In [7]:
one_hot_repr=[one_hot(words,vocab_size) for words in sent]
one_hot_repr

[[4029, 8122, 9560, 1006],
 [4029, 8122, 9560, 6251],
 [4029, 3032, 9560, 1945],
 [5278, 9339, 6445, 8122, 9560, 1006],
 [799, 4029, 976, 9560, 8207],
 [53, 2857, 4852, 7131]]

In [8]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
# from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np

In [20]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 4029 8122 9560 1006]
 [   0    0    0    0 4029 8122 9560 6251]
 [   0    0    0    0 4029 3032 9560 1945]
 [   0    0 5278 9339 6445 8122 9560 1006]
 [   0    0    0  799 4029  976 9560 8207]
 [   0    0    0    0   53 2857 4852 7131]]


In [21]:
## feature representation
dim=10

In [22]:
model = Sequential()
model.add(Embedding(vocab_size, dim, input_length=sent_length))
model.compile('adam', 'mse')

In [23]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 55ms/step


array([[[-0.04134534, -0.00714654, -0.02078099,  0.04614319,
          0.04301636, -0.00080129, -0.00601413, -0.0044596 ,
          0.02993545,  0.0014913 ],
        [-0.04134534, -0.00714654, -0.02078099,  0.04614319,
          0.04301636, -0.00080129, -0.00601413, -0.0044596 ,
          0.02993545,  0.0014913 ],
        [-0.04134534, -0.00714654, -0.02078099,  0.04614319,
          0.04301636, -0.00080129, -0.00601413, -0.0044596 ,
          0.02993545,  0.0014913 ],
        [-0.04134534, -0.00714654, -0.02078099,  0.04614319,
          0.04301636, -0.00080129, -0.00601413, -0.0044596 ,
          0.02993545,  0.0014913 ],
        [-0.00237423,  0.01531525,  0.01900668,  0.04535121,
          0.00646154, -0.0225772 ,  0.0142456 , -0.04753516,
          0.02402166, -0.0217338 ],
        [ 0.01786853, -0.00032721, -0.01747736,  0.01082504,
          0.0316092 ,  0.04286995,  0.00864781,  0.03948125,
          0.02867797, -0.03006982],
        [-0.03127152, -0.02448025,  0.02125353,  0.0

In [24]:
embedded_docs[0]

array([   0,    0,    0,    0, 4029, 8122, 9560, 1006])

In [25]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 55ms/step


array([[-0.04134534, -0.00714654, -0.02078099,  0.04614319,  0.04301636,
        -0.00080129, -0.00601413, -0.0044596 ,  0.02993545,  0.0014913 ],
       [-0.04134534, -0.00714654, -0.02078099,  0.04614319,  0.04301636,
        -0.00080129, -0.00601413, -0.0044596 ,  0.02993545,  0.0014913 ],
       [-0.04134534, -0.00714654, -0.02078099,  0.04614319,  0.04301636,
        -0.00080129, -0.00601413, -0.0044596 ,  0.02993545,  0.0014913 ],
       [-0.04134534, -0.00714654, -0.02078099,  0.04614319,  0.04301636,
        -0.00080129, -0.00601413, -0.0044596 ,  0.02993545,  0.0014913 ],
       [-0.00237423,  0.01531525,  0.01900668,  0.04535121,  0.00646154,
        -0.0225772 ,  0.0142456 , -0.04753516,  0.02402166, -0.0217338 ],
       [ 0.01786853, -0.00032721, -0.01747736,  0.01082504,  0.0316092 ,
         0.04286995,  0.00864781,  0.03948125,  0.02867797, -0.03006982],
       [-0.03127152, -0.02448025,  0.02125353,  0.02037504,  0.03273174,
         0.03822914, -0.0325616 , -0.01201653